---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/rh_integration/httpbin
    newName: quay.io/rh_integration/httpbin
    newTag: smadis
  - name: quay.io/rh_integration/go-httpbin
    newName: quay.io/rh_integration/go-httpbin
    newTag: smadis
  - name: quay.io/rh_integration/requestbin
    newName: quay.io/rh_integration/requestbin
    newTag: latest
  - name: registry.access.redhat.com/rhscl/redis-32-rhel7
    newName: registry.access.redhat.com/rhscl/redis-32-rhel7
    newTag: "3.2"
  - name: quay.io/3scale/echoapi
    newName: quay.io/3scale/echoapi
    newTag: stable
  - name: quay.io/rh_integration/3scale-fuse-camel-proxy
    newName: quay.io/rh_integration/3scale-fuse-camel-proxy
    newTag: latest
  - name: quay.io/rh_integration/tinyproxy
    newName: quay.io/rh_integration/tinyproxy
    newTag: eloy
  - name: quay.io/mganisin/mockserver
    newName: quay.io/mganisin/mockserver
    newTag: latest
  - name: quay.io/rh_integration/jaeger-aio
    newName: quay.io/rh_integration/jaeger-aio
    newTag: latest
  - name: quay.io/minio/minio
    newName: quay.io/minio/minio
    newTag: latest

patchesStrategicMerge:
  - minio-credentials.yaml

resources:
  - ../../base/httpbin/
  - ../../base/go-httpbin/
  - ../../base/request-bin/
  - ../../base/echo-api/
  - ../../base/fuse-proxy/
  - ../../base/tiny-proxy/
  - ../../base/mockserver/
  - ../../base/jaeger/
  - ../../base/minio/
